### ISSUE TITLE
Path error when interface is nested under root namespace

### ISSUE THREAD

**Issue by TonyGravagno** [coozieki/php-implementor#2] opened 2021-12-20 21:24 UTC
This works fine when interface `IBbb` is in folder MAIN/Sub1.

```
namespace MAIN\Sub1;
...
class Aaa implements IBbb{ }
```

This returns a file not found error:

```
namespace MAIN\Sub1;
use MAIN\Sub2\IBbb;
...
class Aaa implements IBbb { }
```

With `php-implementor.autoloads:MAIN` = 'folders', it makes sense that this extension expects the `IBbb` file to be in 'folders/Sub1' and not 'folders/Sub2'. But this is a valid construct and I believe it should recognize the path and file within the current context, with 'use' and other modifications applied - VSCode knows where the file is.

Thanks for this extension and your time.

**Comment by coozieki** [comment] 2021-12-21 07:39
@TonyGravagno Hi, thanks for your feedback! I thought about that. That namespace usage does not really follow the PSR standarts, as "The contiguous sub-namespace names after the "namespace prefix" correspond to a subdirectory within a "base directory", in which the namespace separators represent directory separators. The subdirectory name MUST match the case of the sub-namespace names." https://www.php-fig.org/psr/psr-4/ . But I understand that this case can take place too.

The problem is I actually don't know how to find a file path if it's subnamespace doesn't match it's subdirectory. I could parse the whole project directory to find the file but that would be too slow especially in big projects.

The current possible workaround is adding `"Main\\Sub2": "folders/Sub1"` to the **TOP** of your `php-implementor.autoloads`. But that's not the best solution of course.

**Comment by TonyGravagno** [comment] 2021-12-21 23:58
Thanks for your consideration. I was also thinking about modifying the autoloads array, but I have many files with this code structure.

I'm using Composer and the autoloader. In the composer.json file there is this structure:

```json
    "autoload": {
        "psr-4": {
            "MAIN\\": "inc",
            "MAIN\\Sub1\\": "inc/Sub1/",
            "MAIN\\Sub2\\": "inc/Sub2/",
            "ProjectNamespace\\": "src/"
        }
    }
```

That's how VSCode relates the logical name to the physical. Perhaps you can add a new value in your config:

```json
    "php-implementor.autoloads": {
        "MAIN": "path/to/project/inc"
    },
    "php-implementor.composerPath" : "path/to/project" ,
```
In that folder it should find the composer.json where you can get those values.

**Challenges**

- The composerPath might need to include the filename. I don't know if an alternative name is possible for composer.json but I think not.
- I don't know if there are multiple PSR levels, other than 4, which can be used in that structure. But you require PSR-4 too.
- You might prefer an easier approach which would be for us to copy that structure into your .autoloads value. That would be a small price for a developer to pay for use of this extension.
- The relative path for composer.json seems to start at a different level than you expect. I would really prefer not to have to modify the specs for your extension whenever modifying Composer, though that's a rare event with established code.
- You might be able to add a simple Boolean settings flag "useComposer". From there you can find the composer.json and just use that as an alternative to your own "autoloads" parameter. I think that's a very elegant solution that doesn't require any duplication, adjustments for relative path roots, etc. I think this is the solution here.

**Comment by coozieki** [comment] 2021-12-23 15:05
Closed by dc34de7b998c4d4ebf135da7043f428f9c0e16a4

Added a boolean `php-implementor.useComposerAutoloads` and `php-implementor.composerPath`. By default if you enable `php-implementor.useComposerAutoloads` extension will search for composer.json in the root folder of your workspace. 

By the way composer.json must always be at the root folder of your project, so the only way I see composer.json not being at the root folder is when you're working with several projects in your workspace. So setting `php-implementor.composerPath` will automatically prepend that path to all of the **composer.json autoloads**.

> ```json
>     "autoload": {
>         "psr-4": {
>             "MAIN\\": "inc",
>             "MAIN\\Sub1\\": "inc/Sub1/",
>             "MAIN\\Sub2\\": "inc/Sub2/",
>             "ProjectNamespace\\": "src/"
>         }
>     }
> ```

You actually don't need to specify `"MAIN\\Sub1\\": "inc/Sub1/"` and ` "MAIN\\Sub2\\": "inc/Sub2/"`. Composer will automatically resolve this for you if your project follows the PSR-4 standart.

**Closed as completed** 2021-12-23 15:05 UTC

**Comment by TonyGravagno** [comment] 2021-12-24 20:24
I'd like to re-open this.

In an typical extensible project there can be many composer.json files, one for exact plugin/addon/extension within the project. Example:

```
/path/to/core
/path/to/core/inc
/path/to/core/assets

/path/to/core/plugins
/path/to/core/plugins/plugin1 ...composer.json
/path/to/core/plugins/plugin2 ...composer.json
```

The paths for Composer are relative to the plugin, not the project. That is, the root for Composer is the plugin root, not the project root.

So an unconfigurable default of workspace root does not solve the original problem. Looking back, I made a poor assumption that a Boolean check for Composer would scan folders up from the current file to the nearest composer.json. I recognize that could be non-performant, but given that this is not an always-running process, performance doesn't really matter.

I'll leave the resolution to you of course but I'm thinking the folder scan would be a better solution than workspace root, and wouldn't require a change in the new settings parameter.

Thanks for working with me on this.

**Comment by TonyGravagno** [comment] 2021-12-24 21:11
Here's another suggestion, I think this is the best so far... If `php-implementor.composerPath` is an array like `php-implementor.autoloads`, then the key should be the root namespace or project used in the code. In my examples I've been using "MAIN" as the namespace. Again, the "MAIN" element comes from the code `namespace` declaration, the first element of which could be the same as for all of the `use` statements, but there's no guarantee there. So with my comment above about plugin/addon structures, that results in.

*settings.json*

```json
php-implementor.composerPath: {
   "MAIN": "workspace/relative/path/to/core/plugins/plugin1" // composer.json found here
}
```

*mycode.php*

```php
/** @package  MYPACKAGE */

namespace MAIN\Framework;

use Exception;

use MAIN\Enums\{
    Feature,
    Parameter,
    State,
};
use MAIN\Framework\{
    Cache,
    Singleton,
}
```

*path/to/core/plugins/plugin1/composer.json*

```json
    "autoload": {
        "psr-4": {
            "MAIN\\": "inc",
            "MAIN\\Enums\\": "inc/Enums/",
            "MAIN\\Framework\\": "inc/Framework/",
```

Code can be duplicated in different projects. Consider a file that uses a `class_exists()` to wrap a class that could get defeined in more than one plugin/addon. In this case `namespace` is not guaranteed to be workspace-unique. Similarly, a `@package` could help with disambiguation but it's not guaranteed.

So a suggested hierarchy:

- If `composerPath` is a string, just use that to get to composer.json.
- If `composerPath` is an array, use the keys:
  - If the code has a `@package` declaration, that's the key that points to composer.json.
  - If not, use the first element of the `namespace` declaration as a key.
- If a developer finds ambiguity with two projects in the same package that have the same project and namespace, as a later and only on demand enhancement, perhaps you can add a final fallback to the folder scan-up option: Scan up from the current file for composer.json, stopping at workspace root.

All that said, folder scan-up might completely eliminate the need for use of `php-implementor.composerPath`.

HTH

**Comment by coozieki** [comment] 2021-12-25 00:48
@TonyGravagno I don't think defining root namespace path for every package is the way to go. That would require too much effort from user for just an ide extension. 

Typically all the project dependencies are stored in `vendor/<package_name>` folder and composer.json has all names of packages you use in project. So I can just parse all packages from composer.json and import `autoload` from all composer.json files inside package directories. That wouldn't require any extra actions from user.

**Comment by coozieki** [comment] 2021-12-25 01:04
> Code can be duplicated in different projects. Consider a file that uses a `class_exists()` to wrap a class that could get defeined in more than one plugin/addon. In this case `namespace` is not guaranteed to be workspace-unique. Similarly, a `@package` could help with disambiguation but it's not guaranteed.

Composer packages without vendor namespace is a bad practice and usually the namespaces are unique.

But if that actually happens, to begin with, you wouldn't even be able to properly use these classes. I don't think the extension should take care of such situation.

**Comment by TonyGravagno** [comment] 2021-12-25 19:30
All cool, thanks for the discussion. So given this environment what is the recommended configuration for the extension to get the right composer.json for each plugin?

```
/path/to/core
/path/to/core/inc
/path/to/core/assets

/path/to/core/plugins
/path/to/core/plugins/plugin1 ...composer.json
/path/to/core/plugins/plugin2 ...composer.json
```

This structure is common for all WordPress environments and many other FOSS platforms.

**Comment by coozieki** [comment] 2021-12-25 20:04
@TonyGravagno 

> So I can just parse all packages from composer.json and import `autoload` from all composer.json files inside package directories. That wouldn't require any extra actions from user.

I didn't add that feature yet, but when I'll have done this you would just need to set `php-implementor.useComposerAutoloads=true`. 

So as i said the default folder for composer packages which you get by `composer require <vendor>/<package_name>` is `vendor`. As you have your packages in `plugins` directory, I assume your composer.json looks something like this:

```json
{
  ...
  "config": {
    "vendor-dir": "plugins"
  },
  ...
  "require": {
    "<vendor>/plugin1": "<plugin1_version>",
    "<vendor>/plugin2": "<plugin2_version>"
  },
  ...
  "autoload": {
    "MAIN\\": "inc/"
  },
  ...
}
```

And if your workspace root wolder is the same as your project root all you need to do is to set `php-implementor.useComposerAutoloads=true`. And if it's not you would also have to set `php-implementor.composerPath="<your_composer.json_path>"`. The extension will automatically parse all the composer configurations of the installed plugins.

**Comment by TonyGravagno** [comment] 2022-02-14 21:36
I just wanted to post a ping here to let you know I haven't forgotten about this and will come back to testing sometime this month. All efforts and discussion have been appreciated.
